Initial commit of OpenMetrics output
senx/sensision pull request #38
Opened 2021-12-17 09:56 UTC by hbs

Allows to output OpenMetrics format when sensision.openmetrics is defined as a JVM property.

This does not apply to events, only to metrics exposed via /metrics

Due to the limitation in the types supported by OpenMetrics STRING and BOOLEAN values are not exposed.

Classes, label names and values may be altered to stick to OpenMetrics naming conventions.

2022-08-19 18:23 UTC, steven-gueguen requested changes

2022-08-19 18:23 UTC, steven-gueguen commented on sensision/src/main/java/io/warp10/sensision/OpenMetrics.java
> +    value = value.replaceAll("\\", "\\\\");
This will raise an exception:
`java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\`

2022-08-19 18:23 UTC, steven-gueguen commented on sensision/src/main/java/io/warp10/sensision/Sensision.java
> +  public static final String SENSISION_OPENMETRICS = "sensision.openmetrics";
Please, add missing configuration key to template file

2022-09-13 13:45 UTC, steven-gueguen reviewed
Missing parameter in file SensisionFileJMXAgent.java

2023-08-08 06:56 UTC, hbs commented
PTAL

2023-08-11 13:24 UTC, merged